apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicle-insurance
  template:
    metadata:
      labels:
        app: vehicle-insurance
    spec:
      containers:
        - name: vehicle-insurance
          image: 685248003104.dkr.ecr.us-east-1.amazonaws.com/vehicle-insurance:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URL
              value: "mongodb+srv://ishaanchaturvedi511_db_user:rD5PfhbIGJfpjgzW@cluster0.p19qfhj.mongodb.net/?appName=Cluster0"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
